language: node_js
node_js:
  - "10"
before_deploy: pip install --user awscli
deploy:
  - provider: script
    script: ~/.local/bin/aws s3 sync dist s3://dev-www.openlaw.nz --region=ap-southeast-2 --delete
    skip_cleanup: true
    on:
      branch: dev
  - provider: script
    script: ~/.local/bin/aws s3 sync dist s3://www.openlaw.nz --region=ap-southeast-2 --delete
    skip_cleanup: true
    on:
      branch: master
