version: 0.2
phases:
  install:
    runtime-versions:
        nodejs: 10  
    commands:
      - echo Installing ...
      - yarn install
  pre_build:
    commands:
      - echo Installing pre_build ...
  build:
    commands:
      - echo Build started on `date`
      - yarn build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  base-directory: dist