version: 0.2
phases:
  install:
    runtime-versions:
        nodejs: 10  
    commands:
      - echo Installing ...
      - pip install --upgrade awscli
      - yarn install
  pre_build:
    commands:
      - echo Installing pre_build ...
  build:
    commands:
      - echo Build started on `date`
      - yarn build
  post_build:
    commands:
#      - aws s3 sync dist s3://dev-www.openlaw.nz/ --delete
      - echo sync finished
  files:
    - '**/*'
  base-directory: dist